add_control("crossfader", 1, "cc", 64)
add_control("volume_fader_a", 1, "cc", 65)
add_control("eq_low_a", 1, "cc", 76)
add_control("eq_low_reset_a", 1, "note", 114)
add_control("eq_mid_a", 1, "cc", 78)
add_control("eq_mid_reset_a", 1, "note", 113)
add_control("eq_high_a", 1, "cc", 74)
add_control("eq_high_reset_a", 1, "note", 112)
add_control("volume_fader_b", 1, "cc", 66)
add_control("eq_low_b", 1, "cc", 73)
add_control("eq_low_reset_b", 1, "note", 117)
add_control("eq_mid_b", 1, "cc", 75)
add_control("eq_mid_reset_b", 1, "note", 116)
add_control("eq_high_b", 1, "cc", 77)
add_control("eq_high_reset_b", 1, "note", 115)
add_control("pfl_a", 1, "note", 33)
add_control("pfl_b", 1, "note", 34)
add_control("gain_a", 1, "cc", 72)
add_control("gain_b", 1, "cc", 79)
add_control("master_fader", 1, "cc", 67)
add_control("monitor_source", 1, "cc", 68)
add_control("monitor_fader", 1, "cc", 69)
add_control("select_master", 1, "note", 35)
add_control("select_pfl", 1, "note", 36)

-- out leds

add_control("level_a", 1, "note", 80)
add_control("level_b", 1, "note", 81)

